### ISSUE TITLE
Snippets not showing up in jsx files, only in js

### ISSUE THREAD

**Issue by zenVentzi** [jonkwheeler/styled-components-snippets-vscode#1]
The title pretty much summarises it.  Not sure if this is intentional?

**Comment by Razinsky** [comment]
Nor in ts/tsx files.

**Comment by jonkwheeler** [comment]
Not intentional. I'll look into it. If someone has time and wants to open a PR, please 🤞

**Comment by jonkwheeler** [comment]
These are working in js, jsx, ts, tsx now

**Comment by jonkwheeler** [comment]
download the latest and reload vscode if you have to
