### ISSUE TITLE
Snippets only works outside of 'styled'.

### ISSUE THREAD

**Issue by dongepulango** [jonkwheeler/styled-components-snippets-vscode#3]
I'm noob about this stuff but when I type for example:
```
const Button = styled.button`
    color: scp
`
```
it doesn't work. But when I type "outside" of styled it works. Am I doing something wrong?
Thanks

**Comment by jonkwheeler** [comment]
This seems legit. I hadn't been using VSCode when I built this. I'll need to upgrade it. Thanks.

**Comment by jonkwheeler** [comment]
This has been a pain in my bottom. It's working now, though there's some lag. Working through the lag.
