### ISSUE TITLE
Destructured props in styled component

### ISSUE THREAD

**Issue by marceleq27** [jonkwheeler/styled-components-snippets-vscode#7]
Hi, I saw that there is a shortcut for using props in styled component (`scp`), but i think a good idea is to add a new shortcut with destructured props. Here's my example:

`scpd` (styled component props destructured) => `${ ( { ${1} } ) => ${2} }`

Looking for your thoughts 🙂

**Comment by jonkwheeler** [comment]
I don't mind this @marceleq27 if you find it useful! I'll PR it.

**Comment by marceleq27** [comment]
Thank you, it will help me a lot 😅

**Comment by jonkwheeler** [comment]
It's released https://marketplace.visualstudio.com/items?itemName=jonkwheeler.styled-components-snippets Version 0.9.0

**Comment by jonkwheeler** [comment]
Scratch that, v0.10.0
